/// Flutter icons TechFreneticApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TechFreneticApp
///      fonts:
///       - asset: fonts/TechFreneticApp.ttf
///
///
///
import 'package:flutter/widgets.dart';

class TechFreneticIcons {
  TechFreneticIcons._();

  static const _kFontFam = 'TechFreneticApp';
  static const String? _kFontPkg = null;

  static const IconData share =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shareVideo =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData article =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment =
      IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lightBulb =
      IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
